name: Publish Github Pages Sphinx

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout your repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # 3. Install GDAL system dependencies
    - name: Install GDAL system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gdal-bin libgdal-dev

    # 4. Set GDAL environment variables
    - name: Set GDAL environment variables
      run: |
        export CPLUS_INCLUDE_PATH=/usr/include/gdal
        export C_INCLUDE_PATH=/usr/include/gdal

    # 5. Clear pip cache (optional but recommended for a clean build)
    - name: Clear pip cache
      run: |
        sudo rm -rf ~/.cache/pip

    # 6. Install Python dependencies in a virtual environment
    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r docs/requirements.txt

    # 7. Run sphinx-apidoc
    - name: Generate API documentation
      run: |
        source venv/bin/activate
        sphinx-apidoc -o docs ./

    # 8. Build the HTML docs
    - name: Build HTML documentation
      run: |
        source venv/bin/activate
        sphinx-build -b html docs docs/_build/html

    # 9. Commit and push the generated documentation
    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add -f docs/_build/html docs/*.rst
        git commit -m "Auto-update documentation" || echo "No changes to commit"  # Commit si hay cambios
        git pull --rebase origin main  # Traer los cambios remotos
        git push origin HEAD:main  # Forzar el push a la rama main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
